Начала появляться ошибка на самое первое задание http://joxi.ru/DrlkpRxCdWgOzA  которое я не правила
js-tasks-ru/jsbasic-20221028_iba pull request #4
Opened 2022-11-12 11:35 UTC by ilanabatavraam

2022-11-12 11:36 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-11-12 15:36 UTC, ilanabatavraam commented
Нужна помощь @koalex

2022-11-13 11:27 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-11-13 11:28 UTC, koalex requested changes
Исправить замечание в **2-3**

2022-11-13 11:28 UTC, koalex commented on 2-module/3-task/index.js
> +function sum(a, b) {
Нужно ф-цию `sum` записать внутри объекта т.к. в задании **0-1** была ф-ция с таким же именем и тесты ломаются (это особенность наших тестов)

2022-11-13 12:37 UTC, ilanabatavraam commented on 2-module/3-task/index.js
> +function sum(a, b) {
Готово, спасибо!

2022-11-13 12:37 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-11-13 12:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2022-11-14 06:37 UTC, koalex approved these changes

2022-11-14 06:37 UTC, merged